export const partyProminenceOrder = [
	'Bharatiya Janata Party',
	'Indian National Congress',
	'All India Trinamool Congress',
	'Communist Party of India (Marxist)',
	'Nationalist Congress Party',
	'Bahujan Samaj Party',
	'All India Anna Dravida Munnetra Kazhagam',
	'Dravida Munnetra Kazhagam',
	'Shiv Sena',
	'Telugu Desam Party',
	'Aam Aadmi Party',
	'Samajwadi Party',
	'Rashtriya Janata Dal',
	'Biju Janata Dal',
	'Janta Dal (United)',
	'Yuvajana Sramika Rythu Congress Party',
	'Shiromani Akali Dal',
	'All India Forward Bloc',
	'Rashtriya Lok Dal',
	'Janata Dal (Secular)',
	'All India United Democratic Front',
	'Indian Union Muslim League',
	'Lok Janshakti Party',
	'Jammu & Kashmir National Conference',
	'Mizo National Front',
	'Apna Dal (Soneylal)',
	'All India Majlis-E-Ittehadul Muslimeen',
	'Revolutionary Socialist Party',
	'Jharkhand Mukti Morcha',
	'Pattali Makkal Katchi',
	'Rashtriya Loktantrik Party',
	'Janata Dal',
	'Sikkim Democratic Front',
	'National People’s Party',
	'Desiya Murpokku Dravida Kazhagam',
	'Bharat Rashtra Samithi',
	'Nationalist Democratic Progressive Party',
	'Sikkim Krantikari Morcha',
	"Mizoram People's Conference",
	'Maharashtra Navnirman Sena',
	'Peoples Democratic Party',
	'All Jharkhand Students Union',
	"Bodoland People's Front",
	'Janata Congress Chhattisgarh',
	'Jannayak Janata Party',
	'Goa Forward Party',
	'Communist Party of India (Marxist-Leninist)',
	"Naga People's Front",
	"People's Party of Arunachal",
	'Independent'
];
